apiVersion: v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  template:
    spec:
      containers:
      - name: inventory-service
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"