apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.5.9
          ports:
            - containerPort: 3100
          resources:
            requests:
              cpu: "0.5"
              memory: 256Mi
            limits:
              memory: 512Mi
              cpu: "1"
          args:
            - -config.file=/etc/loki/local-config.yaml
          volumeMounts:
            - name: loki-data
              mountPath: /loki
  volumeClaimTemplates:
    - metadata:
        name: loki-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
