apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:18.1
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 256Mi
              cpu: "0.5"
            limits:
              memory: 512Mi
              cpu: "1"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_password
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql
            - name: postgresql-initdb-config
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgresql-initdb-config
          configMap:
            name: postgresql-initdb-config
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi